name: dev

on:
  repository_dispatch:
    types: [dummy_service_development]

jobs:
  ping-pong:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
          echo "ref name '${{ github.event.client_payload.ref_name }}'"
      - name: PONG - Dispatch response to received PING
        if: github.event.action == 'ping'
        run: |
          curl -X POST https://api.github.com/repos/baotran1989/testing-github/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "pong", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
  BuildAndUnitTests:
    runs-on: ubuntu-latest # Lưu ý: lúc build có thể dùng public runner cho nhanh
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: github.event.client_payload.repository
          ref: github.event.client_payload.sha
          token: secrets.ACCESS_TOKEN
      - name: Set up DotNet SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Test
        run: dotnet test --no-build --configuration Release

  BuildAndPushDockerImage:
    needs: [ BuildAndUnitTests ]
    if: github.event.client_payload.ref_name == 'development'
    runs-on: ubuntu-latest # Lưu ý: lúc build có thể dùng public runner cho nhanh
    outputs:
      DOCKER_IMAGE_TAG: ${{ steps.set_docker_image.outputs.DOCKER_IMAGE_TAG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: github.event.client_payload.repository
          ref: github.event.client_payload.sha
          token: secrets.ACCESS_TOKEN
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Get current date and commit hash
        id: vars
        run: |
          echo "CURRENT_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV
      - name: Build and push container image to registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/izota-dummy:dev-${{ env.CURRENT_DATE }}-${{ github.event.client_payload.sha }}
            ${{ secrets.DOCKER_USERNAME }}/izota-dummy:dev-${{ env.CURRENT_DATE }}
          file: ./Dockerfile
          context: ./
      - name: Set output docker image
        id: set_docker_image
        run: |
          echo "DOCKER_IMAGE_TAG=dev-${{ env.CURRENT_DATE }}-${{ github.event.client_payload.sha }}" >> "$GITHUB_OUTPUT"


  DeployToDev:
    needs: [ BuildAndPushDockerImage ]
    if: github.event.client_payload.ref_name == 'development'
    runs-on: ubuntu-latest
    steps:
      - name: Dummy
        run: |
          echo "VERSION=${{ needs.ReleaseDryRun.outputs.VERSION }}"
          echo "RELEASE_NOTES=${{ needs.ReleaseDryRun.outputs.RELEASE_NOTES }}"
          echo "DOCKER_IMAGE_TAG=${{ needs.BuildAndPushDockerImage.outputs.DOCKER_IMAGE_TAG }}"
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Replace docker image in file deployment
        run: |
          sed -i 's|DOCKER_IMAGE_FRONTEND|${{ secrets.DOCKER_USERNAME }}/izota-dummy:${{ needs.BuildAndPushDockerImage.outputs.DOCKER_IMAGE_TAG }}|g' dummy_service/deployments/frontend/deployment.yaml
          sed -i 's|DOCKER_IMAGE_FRONTEND|${{ secrets.DOCKER_USERNAME }}/izota-dummy:${{ needs.BuildAndPushDockerImage.outputs.DOCKER_IMAGE_TAG }}|g' dummy_service/deployments/frontend/deployment-frontend-2.yaml
          sed -i 's|DOCKER_IMAGE_BACKEND|${{ secrets.DOCKER_USERNAME }}/izota-dummy:${{ needs.BuildAndPushDockerImage.outputs.DOCKER_IMAGE_TAG }}|g' dummy_service/deployments/backend/deployment.yaml
      - name: Deploy Frontend
        run: |
          cat dummy_service/deployments/frontend/deployment.yaml
      - name: Deploy Frontend 2
        run: |
          cat dummy_service/deployments/frontend/deployment-frontend-2.yaml
      - name: Deploy Backend
        run: |
          cat dummy_service/deployments/backend/deployment.yaml